export const LORE: Record<string, string> = {
  "mantle-of-logic":
    "Despite his name he's not actually all knowing, just has a good head between his shoulders. Good leader. Friendlier than most other Mantles, though that's not saying much.",

  "worker-1":
    "Can be assigned to any part of my floor to help with resource gathering and crafting.",

  gaige:
    "Gaige. She runs another department here in the Magnus Factory - something called 'Dust Research and Acquisition' or some such similar nonsense. She's got an ego, thankfully I won't see her too much - at least for now.",

  belling: "",

  emil: "",

  relia: "",

  ylene: "",

  tmp: "A basic metal that's highly malleable yet light and extremely resistant to heat. Perfect for the Perpetual Energy Generator.",

  wood: "It's wood mate not much else to say, though as of seven weeks ago it's no longer a renewable resource - our forests are completely gone and our reserves of wood are charred, hence the name 'Blazer Wood'. Still useful, though limited.",

  rubber:
    "A heat resistant adhesive. This'll be very useful for crafting more complex components in the future.",

  steamDust:
    "Steam that has gone through a dustation period instead of condensing back into water. Thanks to the humidity we get quite a lot of Steam dust, I hate using it though. Just a reminder of how close we are to a point of no return.",

  steamPipe:
    "A thin and flexible pipe that can withstand high pressure and heat. Used to transport steam dust.",

  glass: "Glass... Yep... It's glass.",

  energy:
    "Perpetual Kinetic Energy. The solution to all of our world's problems.",

  gear: "Top gears these are.",

  fittings: "I'll need a lot of these to upgrade my resource storage.",

  beams:
    "Beams made primarily from Blazer Wood, though they need metal reinforcements for structural support.",

  propeller:
    "These have to be very carefully designed. Not only are they for cooling things down but they're also used to keep the PKG in the air. They cannot be an atom heavier than they need to be.",

  vent: "Vents are used to control air flow.",

  boiler:
    "A silver lining of the planet having a heat death is that boiling water is incredibly easy. Though, in my professional opinion, this doesn't exactly outweigh the cost.",

  piston:
    "Pistons are useful to convert energy stores and actually do something with all the pressure we store.",

  pressureValve:
    "Helps to physically regulate pressure. Should stop anything from exploding.",

  governor:
    "This helps to physically regulate speed. Should stop anything from dismantling itself.",

  flywheel:
    "These are used to store rotational kinetic energy. They'll be used in great amount in the PKS.",

  gauge: "A gauge will tell me what's working and what's not working.",

  zephyr: "The jets that will keep PKG in the air ad infinitum.",

  strongbox: "The core containers for the energy stored in the PKS.",

  workers:
    "The backbone of the Magnus Factory, primarily here for resource gathering and crafting. They certainly make my life substantially easier, tough times I suppose.",

  pkg: "My hypothetical 'save-the-world' generator. It hovers in the atmosphere and generates energy from the insane speed of the planets movement through orbit, hence the name 'Perpetual Kinetic Energy'. What could be more perpetual than the orbit of a planet? It's not like it'll get slower.",

  pks: "The storage for the energy generated by the PKG. It can store the energy as auxiliary, kinetic, pressure, tension, torsion, heat, you name it. This is as much of a magnum opus as the generator itself. All one input, about a dozen different outputs.",
};
